algoritmo "trapézio"
// Autor :Miguel Caparroz
// Data : 13/04/2026
var
//Variaveis
   bmaior, bmenor, altura, area:real
inicio
// Seção de Comandos 
   escreva("Informe a altura do trapézio:")
   leia(altura)
   escreva("Informe a base menor do trapézio:")
   leia(bmenor)
   escreva("Informe a base maior do trapézio:")
   leia(bmaior)
   
//calculos

          area<-(bmaior+bmenor)*altura/2

          limpatela
          
//exibir dados

         escreval("A área do trapézio é ",area)


fimalgoritmo
