algoritmo "terreno"
// Autor :Miguel Caparroz
// Data : 13/04/2026
var
//Variaveis
   area, comprimento, largura:real
inicio
// Seção de Comandos 
   escreva("Informe o comprimento do terreno:")
   leia(comprimento)
   escreva("Informe a largura do terreno:")
   leia(largura)
   
//calculos

          area<- largura*comprimento

          limpatela
          
//exibir dados

         escreval("A área do terreno é : ",area)


fimalgoritmo
