algoritmo "IMC"

// Autor : Miguel Caparroz
// Data : 13/04/2026

var
//Variaveis
   peso, altura, final:real
inicio
// Seção de Comandos
   escreva("Informe o seu peso:")
   leia(peso)
   escreva("Informe sua altura:")
   leia(altura)

//calculos

          final<-peso/(altura*altura)

          limpatela

//exibir dados

         escreval("Seu Índice de Massa Corpórea é  : ",final)


fimalgoritmo

